options:
  port:
    type: int
    default: 5000
    description: HTTP port
  backend-mode:
    type: string
    default: development
    description: Which mode out of `development` or `production` the backend server should use
  secure-cookies:
    type: boolean
    default: false
    description: Whether cookies should require HTTPS
