# reusable workflow triggered by other actions
name: CI

on:
  workflow_call:
    secrets:
      charmcraft-credentials:
        required: true

jobs:

  lib-check:
    name: Check libraries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@2.1.1
        with:
          credentials: "${{ secrets.charmcraft-credentials }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt install tox

    - name: Lint code
      run: tox -e lint

  unit:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt install tox

    - name: Run unit tests
      run: tox -e unit

  deploy:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
            provider: microk8s
            channel: 1.22/stable
            charmcraft-channel: latest/candidate
      - name: Run test
        run: |
          sg microk8s -c "microk8s enable ingress metallb:10.64.140.43-10.64.140.49"
          sudo usermod --append --groups lxd $USER
          sudo apt install -y firefox-geckodriver
          # Requires the model to be called kubeflow due to this bug:
          # https://github.com/kubeflow/kubeflow/issues/6136
          juju add-model kubeflow
          sg microk8s -c "tox -e integration -- --model kubeflow"

      - run: sg microk8s -c "microk8s.kubectl get all -A"
        if: failure()

      - run: sg microk8s -c "microk8s.kubectl get pods -A -oyaml"
        if: failure()

      - run: juju status
        if: failure()

      - name: Get kubeflow-volumes workload logs
        run: sg microk8s -c "microk8s.kubectl logs --tail 100 -nkubeflow -ljuju-app=kubeflow-volumes"
        if: failure()

      - name: Get kubeflow-volumes operator logs
        run: sg microk8s -c "microk8s.kubectl logs --tail 100 -nkubeflow -ljuju-operator=kubeflow-volumes"
        if: failure()

      - name: Generate inspect tarball
        run: >
          sg microk8s <<EOF
            microk8s inspect | \
            grep -Po "Report tarball is at \K.+" | \
            xargs -I {} cp {} inspection-report-${{ strategy.job-index }}.tar.gz
          EOF
        if: failure()

      - name: Upload inspect tarball
        uses: actions/upload-artifact@v2
        with:
          name: inspection-reports
          path: ./inspection-report-${{ strategy.job-index }}.tar.gz
        if: failure()

      - name: Upload selenium screenshots
        uses: actions/upload-artifact@v2
        with:
          name: selenium-screenshots
          path: /tmp/selenium-*.png
        if: failure()

      - name: Upload HAR logs
        uses: actions/upload-artifact@v2
        with:
          name: selenium-har
          path: /tmp/selenium-*.har
        if: failure()
