name: CI

on:
  - push
  - pull_request

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt install tox

    - name: Lint code
      run: tox -e lint

  unit:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt install tox

    - name: Run unit tests
      run: tox -e unit

  deploy:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - uses: balchua/microk8s-actions@v0.2.2
      with:
        addons: '["dns", "storage", "rbac"]'

    - name: Install dependencies
      run: |
        set -eux
        sudo pip3 install charmcraft
        sudo snap install juju --classic
        sudo snap install juju-helpers --classic
        sudo snap install juju-wait --classic
        sudo snap install yq

    - name: Bootstrap Juju
      run: |
        set -eux
        sg microk8s -c 'juju bootstrap microk8s uk8s'
        juju add-model ci-test

    - name: Deploy charm
      run: |
        set -eux
        charmcraft build
        juju deploy ./*.charm \
          --resource oci-image=$(yq eval '.resources.oci-image.upstream-source' metadata.yaml)
        juju deploy cs:istio-pilot
        juju relate istio-pilot kubeflow-volumes
        # https://bugs.launchpad.net/juju/+bug/1921739
        (i=60; while ! juju wait -wvt 30 ; do ((--i)) || exit; sleep 1; done)

    - name: Test charm
      run: ls -lath

    - name: Get all
      run: kubectl get all -A
      if: failure()

    - name: Get juju status
      run: juju status
      if: failure()

    - name: Get workload logs
      run: kubectl logs --tail 100 -nci-test -lapp.kubernetes.io/name
      if: failure()

    - name: Get operator logs
      run: kubectl logs --tail 100 -nci-test -loperator.juju.is/name
      if: failure()
