
name: Publish

on:
  push:
    branches:
      - master
      - publish-job # TODO only for debugging purposes remove afterwards

jobs:
  publish-charm:
    name: Publish Charm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: canonical/charmhub-upload-action@initial-implementation
      with:
        credentials: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
